{% set version = "1.0.2" %}

package:
  name: amptools
  version: {{ version }}

source:
  url: https://github.com/usgs/shakemap-amp-tools/archive/{{ version }}.tar.gz
  sha256: b4c388ef6767ef3dda6bfe2ef8c8c0b369dadf39a8b6b49f73fc8d93cced4320

build:
  number: 0
  skip: True  # [py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - lxml
    - numpy
    - obspy
    - openpyxl
    - pandas
    - xlrd
    - xlwt
    - xlsxwriter

test:

  imports:
    - amptools

about:
  home: https://github.com/usgs/shakemap-amp-tools
  license: Public Domain
  summary: 'Fetch and process strong motion waveform/peak amplitude data.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
