{% set version = "1.1.7" %}

package:
  name: amptools
  version: {{ version }}

source:
  url: https://github.com/usgs/shakemap-amp-tools/archive/{{ version }}.tar.gz
  sha256: 76fce3ff70aa1fe6d9d6667ce289d147013d4f7deace88231f3be0b395c611e7

build:
  noarch: python
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - lxml
    - numpy>=1.14
    - obspy
    - openpyxl
    - pandas
    - pyyaml
    - xlrd
    - xlwt
    - xlsxwriter

test:

  imports:
    - amptools

about:
  home: https://github.com/usgs/shakemap-amp-tools
  license: Public Domain
  summary: 'Fetch and process strong motion waveform/peak amplitude data.'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - hschovanec-usgs
