travis:
  secure:
    BINSTAR_TOKEN: ZUxEVoGBCwWHZJJLS9cepUX7pDqV+0281gB2dOBJzjawIStLCrg6VEtiZ9xzaTLKTbk360mVihCG3nC2ElN6uniWsad4/mHIh2Mtr50EWa4WxT1hkDZ5BOpMngUKKrG2JqA/+GfpE1LTDsds1Uvqs1ejq8NAJmNPJoYyvhPdWks4KhHZGwL748Fs0ptgJ0JBHFq/AibXLn79j3WQKQ3k6+nQrE/tWHEc51KB/gPurCap6YRb9dPMhIYzhQTp1hTgX8pzk30rPC6zvpFTpQTENa7niUayd+YjBHgU1u32vs2Ez30IIiyEeoAZaWDWKDNgIWLryL8I9BLE4wnRsDLVenfKsbXnqCij8kUmbyBcaz2ZqIVdo0ONWCJa7QUqKvIdZx093bwzDF2Lz0pyh79SPQmmHcu7jSXXwCGxot9qo53tUXZP32soDRsBE3E7HDs9RZHWGtz8knjIPKdlLKdsMYSmGh8/f8LyI1emdFRLZZzObnc+mV4Q2MHBXJ/H4tVe9g37w8RH+EzNzXDr2azta14QP7OofhRB/t/c2N4YYNSHjbMMr4xM4VI1bwU2n8nendrtlue54tqjOychZ4nip+i4NFP5KnfGC6GTNIgRIqhKe5nulMDlsUmzUNuc4PESKuuxApT3QkEMY7JUQQY/xsChrpS38VFapLPGPV88vK8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
