travis:
  secure:
    BINSTAR_TOKEN: Bb4x2nfEzNFsmjrjOeqFmJRgh9shnX6urBz40HqyhGWnCu+MGIbGJET2g3d0hYOpsapFIS7j5+8oxmuQMrbQzE3viqA3AFRdGo/xrUWUOBX1bAOi4QNwK8liQFml/JPuafO7ZwYMC2d/gPQ+GSw0d2YnY/opzdRNfn2Bd+Ehs/RByQDs7mAzcleajFhqhRjbZSN+615ARISVfl1NFbBO0Ti6+W90QqMlQ5cCkbqhIMbDgJi9TKVColAtJPWyS/cdSiVShfLEjz8elrZ2/d5FlCEGpLaebTf9CHj4yuXEb5ujZUgd5Qck9vquxvKFgteJ6eL+miiGsAbHIMcmqVZgJIyXk3Zp0praiiOfItJRX7QmTwOcgmBNzE0B7IcVCIRRdIzkeOIl/V5hjRIdIPKh+TG/dUIg49Pat0aNVRxpcmCOkAgvsUFx9H1vGEH2zLZpymjo23q+YmnMlBYVIvQbytY6rC5TwlQuWhR4E+bTCd9t9GB3k0If696AcYoM7GLLfRXX1/wrdhNtqh3Gs6QY+cv3BwMSz5CLg/aS+/ohhTI3WS6fKp/rXeoXCAT54sKCaMZ9WCj2V1DF1/bIKfesGtpNDn2WIO9vRMkFvBxMKEtyZRux7OZdiddTshhPvpiaHTA2KF5dUZ9Tz8vjoQr2Z/qlJG4DDJvNM3UGHkNfBRM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
