travis:
  secure:
    BINSTAR_TOKEN: FJgAwlMi1sKMy7RYjFdK5w0y9myNKbGoDh0VQ74t0hbe1FlHM1t4ar77Wo8WdF1Dyk9g3ZVsTtNo1bhe9sYuJ8jeAkBIDhr6hnyYRPdQ4MmzOhNYzootZhxnWbzDqsaQHe+CoS0IARrpHnzrkxuaAzliyMY5rkvcizsz3zNg3OQWmXLc3phK8MFzH8NmrmWRU2Hqr5aJymwTXiuvSrrn1eXuL+ZST1S25V7jzJu+UcVSfIbZWxqwcZpQqUl+2YmH1gGdZmHKTBZqjXrBL1R6grVtD1xLoeNd3GM0ZJ4o+urH4Zp5kOUdpchOiTC708X+4MGfvkPxQrR7RTWHZ3C3aJRsjmMBuPRfOhlZIjcAa869CemCD4zMBHkAkFFKrvSei2bJWv1PIt7sv52o3cb8lNqC7dTVKgX/8lge+cgBMk/2pMdUCLEusiB3JCEy5r+2fCY+aG8L/1K9bSZ2sp3D098O/axg7j4ZnBsy+S+bnmpFuidy8XDD7dRF/JOkwAmc1v0iHNURyQUwKxL1NKFyLaY4N8mSgyHvV0TPfhzToYoSZmuI3rFIiQyUZqtku8/7O6ea1nPF3VZfi8A/Nh+/L/ywSTSibYeOnDRP2hbqgyw4uT8bwtqTwC4WzruWvYRZqwHKWUUlRS/kPP9032vuCu9tAZiXMs5vjQ4qU719+6w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
